name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
    
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Running the Python script
        run: |
          sudo chmod +x bin/v2ray
          curl -L ${{ secrets.KY_GITHUB_URL }} > bin/ky-github.json && bin/v2ray -config bin/ky-github.json & sleep 4 && curl -x 127.0.0.1:1085 -L https://example.com &
          sleep 4
          sudo git clone https://github.com/FlareSolverr/FlareSolverr && cd FlareSolverr && sudo pip install -r requirements.txt && sudo python src/flaresolverr.py &
          python Selenium-Template.py https://javgg.net/new-post > javgg.html
          #抓supjav
          python Selenium-Template.py https://supjav.com/category/amateur > supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav >> supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav/page/2 >> supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav/page/3 >> supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav/page/4 >> supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav/page/5 >> supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav/page/6 >> supjav.html
          python Selenium-Template.py https://supjav.com/category/censored-jav/page/7 >> supjav.html

          #删除bin/ky-github.json
          rm -rf bin/ky-github.json
          
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
